<!-- MAIN QUESTION: HOW DOES PAGINATION WORKS -->
<!-- IklanDetails.aspx?refNo=PRO250619100555461 -->
 <!-- PRO 250619 10 0555461 -->
 <!-- PRO 250617 10 4353328 -->
<form method="post" action="./IklanList.aspx" id="form1">
<div class="aspNetHidden">
<input type="hidden" name="ToolkitScriptManager1_HiddenField" id="ToolkitScriptManager1_HiddenField" value="">
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="">
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="">
<input type="hidden" name="__LASTFOCUS" id="__LASTFOCUS" value="">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTA5NjA0MTUxOQ9kFgJmD2QWAgIED2QWBgIDDw8WAh4HVmlzaWJsZWhkZAIFDw8WAh8AaGRkAgcPZBYGAgkPZBYEZg9kFgICAw8QZA8WBmYCAQICAgMCBAIFFgYQBShQZWphYmF0IFNldGlhdXNhaGEgS2VyYWphYW4gTmVnZXJpIFBlcmFrBQExZxAFEkphYmF0YW4gS2VyamEgUmF5YQUBMmcQBRhQZWphYmF0IERhZXJhaCBEYW4gVGFuYWgFATNnEAUdSmFiYXRhbiBQZW5nYWlyYW4gRGFuIFNhbGlyYW4FATRnEAUeTGVtYmFnYSBQZXJ1bWFoYW4gZGFuIEhhcnRhbmFoBQE1ZxAFEUphYmF0YW4gUGVydGFuaWFuBQE4ZxYBAgFkAgEPZBYGAgEPEGQPFg1mAgECAgIDAgQCBQIGAgcCCAIJAgoCCwIMFg0QBQtCYWdhbiBEYXR1awUCNzhnEAUNQmF0YW5nIFBhZGFuZwUCNzNnEAULSGlsaXIgUGVyYWsFAjcyZxAFEkh1bHUgUGVyYWsgKEdlcmlrKQUCNzFnEAUGS2FtcGFyBQI3N2cQBQZLZXJpYW4FAjcwZxAFBUtpbnRhBQI2OGcQBQ1LdWFsYSBLYW5nc2FyBQI2OWcQBRhMYXJ1dCwgTWF0YW5nIERhbiBTZWxhbWEFAjc0ZxAFB01hbmp1bmcFAjY3ZxAFB011YWxsaW0FAjc2ZxAFDE5lZ2VyaSBQZXJhawUCNjZnEAUMUGVyYWsgVGVuZ2FoBQI3NWcWAQILZAIDDxBkZBYAZAIFDxBkDxYHZgIBAgICAwIEAgUCBhYHEAUFVGFodW4FBVRhaHVuZxAFBDIwMjUFBDIwMjVnEAUEMjAyNAUEMjAyNGcQBQQyMDIzBQQyMDIzZxAFBDIwMjIFBDIwMjJnEAUEMjAyMQUEMjAyMWcQBQQyMDIwBQQyMDIwZxYBZmQCCw8WAh8AZxYEZg9kFgJmD2QWBAIBDw8WAh8AaGRkAgMPFgweDVN0YXJ0Um93SW5kZXgCBx4LTWF4aW11bVJvd3MCBx4JVG90YWxSb3dzAhYeCkRhdGFTb3VyY2UyyVgAAQAAAP////8BAAAAAAAAAAwCAAAATlN5c3RlbS5EYXRhLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OQUBAAAAE1N5c3RlbS5EYXRhLkRhdGFTZXQDAAAAF0RhdGFTZXQuUmVtb3RpbmdWZXJzaW9uCVhtbFNjaGVtYQtYbWxEaWZmR3JhbQMBAQ5TeXN0ZW0uVmVyc2lvbgIAAAAJAwAAAAYEAAAAtwk8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJ1dGYtMTYiPz4NCjx4czpzY2hlbWEgaWQ9Ik5ld0RhdGFTZXQiIHhtbG5zPSIiIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIgeG1sbnM6bXNkYXRhPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOnhtbC1tc2RhdGEiPg0KICA8eHM6ZWxlbWVudCBuYW1lPSJOZXdEYXRhU2V0IiBtc2RhdGE6SXNEYXRhU2V0PSJ0cnVlIiBtc2RhdGE6VXNlQ3VycmVudExvY2FsZT0idHJ1ZSI+DQogICAgPHhzOmNvbXBsZXhUeXBlPg0KICAgICAgPHhzOmNob2ljZSBtaW5PY2N1cnM9IjAiIG1heE9jY3Vycz0idW5ib3VuZGVkIj4NCiAgICAgICAgPHhzOmVsZW1lbnQgbmFtZT0iVGFibGUiPg0KICAgICAgICAgIDx4czpjb21wbGV4VHlwZT4NCiAgICAgICAgICAgIDx4czpzZXF1ZW5jZT4NCiAgICAgICAgICAgICAgPHhzOmVsZW1lbnQgbmFtZT0icmVmTm8iIHR5cGU9InhzOnN0cmluZyIgbXNkYXRhOnRhcmdldE5hbWVzcGFjZT0iIiBtaW5PY2N1cnM9IjAiIC8+DQogICAgICAgICAgICAgIDx4czplbGVtZW50IG5hbWU9IlByb05vIiB0eXBlPSJ4czpzdHJpbmciIG1zZGF0YTp0YXJnZXROYW1lc3BhY2U9IiIgbWluT2NjdXJzPSIwIiAvPg0KICAgICAgICAgICAgICA8eHM6ZWxlbWVudCBuYW1lPSJUYWp1ayIgdHlwZT0ieHM6c3RyaW5nIiBtc2RhdGE6dGFyZ2V0TmFtZXNwYWNlPSIiIG1pbk9jY3Vycz0iMCIgLz4NCiAgICAgICAgICAgICAgPHhzOmVsZW1lbnQgbmFtZT0iSWtsYW5TdGFydERhdGUiIHR5cGU9InhzOmRhdGVUaW1lIiBtc2RhdGE6dGFyZ2V0TmFtZXNwYWNlPSIiIG1pbk9jY3Vycz0iMCIgLz4NCiAgICAgICAgICAgICAgPHhzOmVsZW1lbnQgbmFtZT0iSWtsYW5FbmREYXRlIiB0eXBlPSJ4czpkYXRlVGltZSIgbXNkYXRhOnRhcmdldE5hbWVzcGFjZT0iIiBtaW5PY2N1cnM9IjAiIC8+DQogICAgICAgICAgICAgIDx4czplbGVtZW50IG5hbWU9IlNpdGVWaXNpdCIgdHlwZT0ieHM6c3RyaW5nIiBtc2RhdGE6dGFyZ2V0TmFtZXNwYWNlPSIiIG1pbk9jY3Vycz0iMCIgLz4NCiAgICAgICAgICAgIDwveHM6c2VxdWVuY2U+DQogICAgICAgICAgPC94czpjb21wbGV4VHlwZT4NCiAgICAgICAgPC94czplbGVtZW50Pg0KICAgICAgPC94czpjaG9pY2U+DQogICAgPC94czpjb21wbGV4VHlwZT4NCiAgPC94czplbGVtZW50Pg0KPC94czpzY2hlbWE+BgUAAADpTDxkaWZmZ3I6ZGlmZmdyYW0geG1sbnM6bXNkYXRhPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOnhtbC1tc2RhdGEiIHhtbG5zOmRpZmZncj0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTp4bWwtZGlmZmdyYW0tdjEiPjxOZXdEYXRhU2V0PjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlMSIgbXNkYXRhOnJvd09yZGVyPSIwIj48cmVmTm8+UFJPMjUwNjE5MTAwNTU1NDYxPC9yZWZObz48UHJvTm8+U0gvTlNDL04vSktSL0pNTi9NZWsgMDMvMjAyNTwvUHJvTm8+PFRhanVrPlNJU1RFTSBQRU5ZQU1BTiBEQU4gUEVOR0FMSUhBTiBVREFSQSBCQUdJIFBST0pFSyBQRU1CSU5BQU4gREVXQU4gU0VSQkFHVU5BIERBTiBLRVJKQS1LRVJKQSBCRVJLQUlUQU4gREkgS0VESUFNQU4gUkFTTUkgWS5BLkIuIE1FTlRFUkkgQkVTQVIgUEVSQUs8L1RhanVrPjxJa2xhblN0YXJ0RGF0ZT4yMDI1LTA3LTAzVDAwOjAwOjAwKzA4OjAwPC9Ja2xhblN0YXJ0RGF0ZT48SWtsYW5FbmREYXRlPjIwMjUtMDctMTRUMTI6MDA6MDArMDg6MDA8L0lrbGFuRW5kRGF0ZT48U2l0ZVZpc2l0PjE8L1NpdGVWaXNpdD48L1RhYmxlPjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlMiIgbXNkYXRhOnJvd09yZGVyPSIxIj48cmVmTm8+UFJPMjUwNjE3MTA0MzUzMzI4PC9yZWZObz48UHJvTm8+U0gvUC9KS1IvSk1OL1NGTS9NZWsgMTkvMjAyNTwvUHJvTm8+PFRhanVrPktFUkpBLUtFUkpBIE1FTUJFS0FMLCBNRU1BU0FORyBEQU4gTUVOR1VKSVRFUklNQSBTSVNURU0gUEVOWUFNQU4gVURBUkEgQkFHSSBQUk9KRUsgTUVOQUlLVEFSQUYgREFOIFBFTkdVQkFIU1VBSUFOIFJVQU5HIFBFSkFCQVQgQkFIQVJVIEpBQkFUQU4gUEVOREFGVEFSQU4gTkVHQVJBIChKUE4pIERBRVJBSCBLSU5UQSwgQkFUVSBHQUpBSCwgUEVSQUsgREFSVUwgUklEWlVBTi48L1RhanVrPjxJa2xhblN0YXJ0RGF0ZT4yMDI1LTA2LTI0VDAwOjAwOjAwKzA4OjAwPC9Ja2xhblN0YXJ0RGF0ZT48SWtsYW5FbmREYXRlPjIwMjUtMDctMDlUMTI6MDA6MDArMDg6MDA8L0lrbGFuRW5kRGF0ZT48U2l0ZVZpc2l0PjE8L1NpdGVWaXNpdD48L1RhYmxlPjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlMyIgbXNkYXRhOnJvd09yZGVyPSIyIj48cmVmTm8+UFJPMjUwNjE4MDgzMjI3MjM2PC9yZWZObz48UHJvTm8+SktSLkt0YS5QZXIuU0dCIDM0LzIwMjU8L1Byb05vPjxUYWp1az5LRVJKQS1LRVJKQSBQRU5HVUJBSFNVQUlBTiBSVUFORyBQRUpBQkFUIEJBSEFSVSBKQUJBVEFOIFBFTkRBRlRBUkFOIE5FR0FSQSAoSlBOKSBCQVRVIEdBSkFIPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0zMFQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA3LTA3VDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4xPC9TaXRlVmlzaXQ+PC9UYWJsZT48VGFibGUgZGlmZmdyOmlkPSJUYWJsZTQiIG1zZGF0YTpyb3dPcmRlcj0iMyI+PHJlZk5vPlBSTzI1MDYxNjA5NDMwMTg1NTwvcmVmTm8+PFByb05vPkpLUi5CRC5TSC4gMDUvMjAyNTwvUHJvTm8+PFRhanVrPktFUkpBLUtFUkpBIFBFTllFTEVOR0dBUkFBTiBQQVZFTUVOIERFTkdBTiBLQUVEQUggUkVHVUxBVEUgJmFtcDsgT1ZFUkxBWSBEQU4gTEFJTi1MQUlOIEtFUkpBIEJFUktBSVRBTiwgREkgU0cgU0FNQUstU0cgTUFOSUxBIDEsIExBTFVBTiBBMjU1LCBTRUtTWUVOIDEzLjAwLTE1LjAwIERBTiBESSBLRyBTRyBNQU5JTEEsIExBTFVBTiBBQTAxLCBTRUtTWUVOIDAuMDAtMS4wMCwgREFFUkFIIEJBR0FOIERBVFVLLCBQRVJBSzwvVGFqdWs+PElrbGFuU3RhcnREYXRlPjIwMjUtMDYtMjZUMDA6MDA6MDArMDg6MDA8L0lrbGFuU3RhcnREYXRlPjxJa2xhbkVuZERhdGU+MjAyNS0wNy0wM1QxMjowMDowMCswODowMDwvSWtsYW5FbmREYXRlPjxTaXRlVmlzaXQ+MjwvU2l0ZVZpc2l0PjwvVGFibGU+PFRhYmxlIGRpZmZncjppZD0iVGFibGU1IiBtc2RhdGE6cm93T3JkZXI9IjQiPjxyZWZObz5QUk8yNTA2MTgxMDQ1MjYzMjM8L3JlZk5vPjxQcm9Obz5KS1IuSFUuUEsoVUIpKE4pMjAvMTAvMjVKTE4gMTAvMjAyNTwvUHJvTm8+PFRhanVrPlNFTkdHQVJBIENFUlVOIFJVTlRVSCBEQU4gS0VSSkEtS0VSSkEgQkVSS0FJVEFOIERJIFRBTUFOIEJBTkRBUiBCQVJVIExFTkdHT05HLCBEQUVSQUggTEVOR0dPTkc8L1RhanVrPjxJa2xhblN0YXJ0RGF0ZT4yMDI1LTA2LTI2VDAwOjAwOjAwKzA4OjAwPC9Ja2xhblN0YXJ0RGF0ZT48SWtsYW5FbmREYXRlPjIwMjUtMDctMDNUMTI6MDA6MDArMDg6MDA8L0lrbGFuRW5kRGF0ZT48U2l0ZVZpc2l0PjE8L1NpdGVWaXNpdD48L1RhYmxlPjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlNiIgbXNkYXRhOnJvd09yZGVyPSI1Ij48cmVmTm8+UFJPMjUwNjE4MTA0NzM0MDIxPC9yZWZObz48UHJvTm8+SktSLkhVLlBLKFVCKShOKTIwLzExLzI1SkxOIDExLzIwMjU8L1Byb05vPjxUYWp1az5TRU5HR0FSQSBDRVJVTiBSVU5UVUggREFOIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBQRVJLQU1QVU5HQU4gVEVSU1VTVU4gQlVLSVQgUkFKQSwgREFFUkFIIExFTkdHT05HPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0yNlQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA3LTAzVDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4xPC9TaXRlVmlzaXQ+PC9UYWJsZT48VGFibGUgZGlmZmdyOmlkPSJUYWJsZTciIG1zZGF0YTpyb3dPcmRlcj0iNiI+PHJlZk5vPlBSTzI1MDYxODEwNDkwNTM1NDwvcmVmTm8+PFByb05vPkpLUi5IVS5QSyhVQikoTikyMC8xMi8yNUpMTiAxMi8yMDI1PC9Qcm9Obz48VGFqdWs+U0VOR0dBUkEgQ0VSVU4gUlVOVFVIIERBTiBLRVJKQS1LRVJKQSBCRVJLQUlUQU4gREkgUlBBIEJVS0lUIFNFTllVTSwgREFFUkFIIExFTkdHT05HPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0yNlQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA3LTAzVDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4xPC9TaXRlVmlzaXQ+PC9UYWJsZT48VGFibGUgZGlmZmdyOmlkPSJUYWJsZTgiIG1zZGF0YTpyb3dPcmRlcj0iNyI+PHJlZk5vPlBSTzI1MDYxOTEyNTYxNDc1NDwvcmVmTm8+PFByb05vPkpLUi5VVEEvU0goVFBHKUVMQyA0LzIwMjU8L1Byb05vPjxUYWp1az5LRVJKQS1LRVJKQSAgUEVOWUVMRU5HR0FSQUFOIEVMRUtUUklLIFZPTFRBTiBTRURFUkhBTkEgMTFLViBEQU4gTEFJTi1MQUlOIEtFUkpBIEJFUktBSVRBTiBESSBLRU0tS0VNIFRFTlRFUkEgREFSQVQsIFRBSVBJTkcsIFBFUkFLIERBUlVMIFJJRFpVQU4uPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0yNFQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA3LTAxVDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4yPC9TaXRlVmlzaXQ+PC9UYWJsZT48VGFibGUgZGlmZmdyOmlkPSJUYWJsZTkiIG1zZGF0YTpyb3dPcmRlcj0iOCI+PHJlZk5vPlBSTzI1MDYxODE0MjYzNTc5MTwvcmVmTm8+PFByb05vPkpLUihFKVBLL1NIKFBZKTYxLzIwMjVCR04gMTIyLzIwMjU8L1Byb05vPjxUYWp1az5LRVJKQS1LRVJKQSBQRU5ZRUxFTkdHQVJBQU4gRUxFS1RSSUsgREFOIFBFTkRBV0FJQU4gU0VNVUxBIFNFUlRBIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBCTE9LIFBFSkFCQVQsIFBVU0FUIFNVTUJFUiBEQU4gU1VSQVUgREkgS09MRUogVk9LQVNJT05BTCBTTElNIFJJVkVSLCBEQUVSQUggTVVBTExJTSwgUEVSQUsgREFSVUwgUklEWlVBTjwvVGFqdWs+PElrbGFuU3RhcnREYXRlPjIwMjUtMDYtMjNUMDA6MDA6MDArMDg6MDA8L0lrbGFuU3RhcnREYXRlPjxJa2xhbkVuZERhdGU+MjAyNS0wNi0zMFQxMjowMDowMCswODowMDwvSWtsYW5FbmREYXRlPjxTaXRlVmlzaXQ+MjwvU2l0ZVZpc2l0PjwvVGFibGU+PFRhYmxlIGRpZmZncjppZD0iVGFibGUxMCIgbXNkYXRhOnJvd09yZGVyPSI5Ij48cmVmTm8+UFJPMjUwNjE4MTcwMzUwNDU1PC9yZWZObz48UHJvTm8+SktSLktSTi5KTE4gMTYvMjAyNTwvUHJvTm8+PFRhanVrPktFUkpBIFBFUkFXQVRBTiBBU0FTIEpBTEFOIFlBTkcgTUVOREFQIERBTiBQRU1CQUlLQU4gVElBTkcgTEFNUFUgSVNZQVJBVCBDT05ET05HIFNFUlRBIEtFUkpBIEJFUktBSVRBTiBESSBTRUtTWUVOIDAuNCwgSkFMQU4gS1VBTEEgS1VSQVUgLSBCQUdBTiBTRVJBSSAoRlQwNzUpLCBEQUVSQUggS0VSSUFOLCBQRVJBSzwvVGFqdWs+PElrbGFuU3RhcnREYXRlPjIwMjUtMDYtMjNUMDA6MDA6MDArMDg6MDA8L0lrbGFuU3RhcnREYXRlPjxJa2xhbkVuZERhdGU+MjAyNS0wNi0zMFQxMjowMDowMCswODowMDwvSWtsYW5FbmREYXRlPjxTaXRlVmlzaXQ+MjwvU2l0ZVZpc2l0PjwvVGFibGU+PFRhYmxlIGRpZmZncjppZD0iVGFibGUxMSIgbXNkYXRhOnJvd09yZGVyPSIxMCI+PHJlZk5vPlBSTzI1MDUxNjE1MzkwMzU4NjwvcmVmTm8+PFByb05vPkpLUi5LdGEuTmVnLlNHQiAzMS8yMDI1PC9Qcm9Obz48VGFqdWs+S0VSSkEtS0VSSkEgVUJBSFNVQUkgUlVBTkcgUEVKQUJBVCBCQUhBUlUgKEFSQVMgNSkgSkFCQVRBTiBNVUZUSSBORUdFUkkgUEVSQUsgREFSVUwgUklEWlVBTiBESSBCQU5HVU5BTiBTU00gSVBPSDwvVGFqdWs+PElrbGFuU3RhcnREYXRlPjIwMjUtMDYtMTlUMDA6MDA6MDArMDg6MDA8L0lrbGFuU3RhcnREYXRlPjxJa2xhbkVuZERhdGU+MjAyNS0wNi0yNlQxMjowMDowMCswODowMDwvSWtsYW5FbmREYXRlPjxTaXRlVmlzaXQ+MTwvU2l0ZVZpc2l0PjwvVGFibGU+PFRhYmxlIGRpZmZncjppZD0iVGFibGUxMiIgbXNkYXRhOnJvd09yZGVyPSIxMSI+PHJlZk5vPlBSTzI1MDYxMTE0MTkwNTAzODwvcmVmTm8+PFByb05vPlNIL04vSktSL0pNTi9TRk0vTWVrIDIwLzIwMjU8L1Byb05vPjxUYWp1az5LRVJKQS1LRVJKQSBNRU5BSUtUQVJBRiBLRU1BU0FOIERBTEFNQU4gTElGIChJTlRFUklPUiBERVNJR04pIEJBR0kgTElGIDIsIExJRjMgREFOIExJRiA2IERJIEJBTkdVTkFOIFBFUkFLIERBUlVMIFJJRFpVQU48L1RhanVrPjxJa2xhblN0YXJ0RGF0ZT4yMDI1LTA2LTE5VDAwOjAwOjAwKzA4OjAwPC9Ja2xhblN0YXJ0RGF0ZT48SWtsYW5FbmREYXRlPjIwMjUtMDYtMjZUMTI6MDA6MDArMDg6MDA8L0lrbGFuRW5kRGF0ZT48U2l0ZVZpc2l0PjE8L1NpdGVWaXNpdD48L1RhYmxlPjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlMTMiIG1zZGF0YTpyb3dPcmRlcj0iMTIiPjxyZWZObz5QUk8yNTA2MTIxMDM5NTc3MTI8L3JlZk5vPjxQcm9Obz5KS1IuVVRBL1NIKFRQRylBd2FtIDQvMjAyNTwvUHJvTm8+PFRhanVrPktFUkpBIFBFTUJBSUtBTiBBV0FNIEJBR0kgU0lTVEVNIEJFS0FMQU4gQUlSIERBTiBTSVNURU0gUElMSSBCT01CQSBESSBQQVNVS0FOIFJFSklNRU4gS0UtMyBBUlRJTEVSSSBESVJBSkEgKDMgUkFEKSwgS0VNIEtBTVVOVElORywgUEVSQUs8L1RhanVrPjxJa2xhblN0YXJ0RGF0ZT4yMDI1LTA2LTE5VDAwOjAwOjAwKzA4OjAwPC9Ja2xhblN0YXJ0RGF0ZT48SWtsYW5FbmREYXRlPjIwMjUtMDYtMjZUMTI6MDA6MDArMDg6MDA8L0lrbGFuRW5kRGF0ZT48U2l0ZVZpc2l0PjI8L1NpdGVWaXNpdD48L1RhYmxlPjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlMTQiIG1zZGF0YTpyb3dPcmRlcj0iMTMiPjxyZWZObz5QUk8yNTA2MTMxNjQyMDkwNDE8L3JlZk5vPjxQcm9Obz5KS1IoRSlQSy9TSChQWSk2My8yMDI1SkxOIDExOC8yMDI1PC9Qcm9Obz48VGFqdWs+S0VSSkEtS0VSSkEgUEVNQkFJS0FOIExBTVBVIEpBTEFOIFVOVFVLIEpBTEFOIFBFUlNFS1VUVUFOIFNFUlRBIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBKQUxBTiBJUE9IIC0gTFVNVVQgRlQgMDA1IFNFS1NZRU4gNjc0IEhJTkdHQSBTRUtTWUVOIDY3MywgUEVSQUsgVEVOR0FILCBQRVJBSyBEQVJVTCBSSURaVUFOPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0xOVQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA2LTI2VDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4yPC9TaXRlVmlzaXQ+PC9UYWJsZT48VGFibGUgZGlmZmdyOmlkPSJUYWJsZTE1IiBtc2RhdGE6cm93T3JkZXI9IjE0Ij48cmVmTm8+UFJPMjUwNjEzMTY1MDAzNDQ1PC9yZWZObz48UHJvTm8+SktSKEUpUEsvU0goUFkpNjIvMjAyNUpMTiAxMTcvMjAyNTwvUHJvTm8+PFRhanVrPktFUkpBLUtFUkpBIE5BSUtUQVJBRiBEQU4gU0VMRU5HR0FSQSBMQU1QVSBKQUxBTiBURVJNQVNVSyBLRVJKQS1LRVJKQSBCRVJLQUlUQU4gREkgTEFMVUFOIEZUMDc2IEpBTEFOIEsuIEtBTkdTQVIgLSBHRVJJSyAtIFBFTkdLQUxBTiBIVUxVIChKQUxBTiBHRVJJSyAtIEJBVFUgMiBGL1AgMikgREkgREFFUkFIIEhVTFUgUEVSQUssIFBFUkFLPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0xOVQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA2LTI2VDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4yPC9TaXRlVmlzaXQ+PC9UYWJsZT48VGFibGUgZGlmZmdyOmlkPSJUYWJsZTE2IiBtc2RhdGE6cm93T3JkZXI9IjE1Ij48cmVmTm8+UFJPMjUwNjE0MTEwMTIwODQ5PC9yZWZObz48UHJvTm8+SktSKEUpUEsvU0goUFkvTik0NC8yMDI1SkxOIDExOS8yMDI1PC9Qcm9Obz48VGFqdWs+S0VSSkEtS0VSSkEgUEVOWUVMRU5HR0FSQUFOIExBTVBVIElTWUFSQVQgREkgSkFMQU4gVEFOSlVORyBNQUxJTSBBMDMwIFNFUlRBIEtFUkpBLUtFUkpBIFlBTkcgQkVSS0FJVEFOIERBRVJBSCBNVUFMTElNIFBFUkFLIERBUlVMIFJJRFpVQU48L1RhanVrPjxJa2xhblN0YXJ0RGF0ZT4yMDI1LTA2LTE5VDAwOjAwOjAwKzA4OjAwPC9Ja2xhblN0YXJ0RGF0ZT48SWtsYW5FbmREYXRlPjIwMjUtMDYtMjZUMTI6MDA6MDArMDg6MDA8L0lrbGFuRW5kRGF0ZT48U2l0ZVZpc2l0PjI8L1NpdGVWaXNpdD48L1RhYmxlPjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlMTciIG1zZGF0YTpyb3dPcmRlcj0iMTYiPjxyZWZObz5QUk8yNTA2MTYxMzE2NTMzNDA8L3JlZk5vPjxQcm9Obz5KS1IoRSlQSy9TSChQWSk1OS8yMDI1QkdOIDEyMS8yMDI1PC9Qcm9Obz48VGFqdWs+S0VSSkEtS0VSSkEgUEVOREFXQUlBTiBTRU1VTEEgRUxFS1RSSUsgREFOIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBQRUpBQkFUIEJBUlUgSkFCQVRBTiBQRU5EQUZUQVJBTiBORUdBUkEgKEpQTikgQkFUVSBHQUpBSCBCRVJBTEFNQVQgTk8gNiAmYW1wOyA3IChHUk9VTkQgRkxPT1IpLCBQRVJTSUFSQU4gQkFUVSBHQUpBSCBQRVJEQU5BIDEsIFBVU0FUIEtPTUVSU0lBTCwgQkFUVSBHQUpBSCBQRVJEQU5BLCBQRVJBSzwvVGFqdWs+PElrbGFuU3RhcnREYXRlPjIwMjUtMDYtMTlUMDA6MDA6MDArMDg6MDA8L0lrbGFuU3RhcnREYXRlPjxJa2xhbkVuZERhdGU+MjAyNS0wNi0yNlQxMjowMDowMCswODowMDwvSWtsYW5FbmREYXRlPjxTaXRlVmlzaXQ+MjwvU2l0ZVZpc2l0PjwvVGFibGU+PFRhYmxlIGRpZmZncjppZD0iVGFibGUxOCIgbXNkYXRhOnJvd09yZGVyPSIxNyI+PHJlZk5vPlBSTzI1MDYxNzA5NDIyNjM3NTwvcmVmTm8+PFByb05vPkpLUihFKVBLL1NIKFBZKTY0LzIwMjVCR04gMTIwLzIwMjU8L1Byb05vPjxUYWp1az5LRVJKQS1LRVJKQSBQRU5EQVdBSUFOIFNFTVVMQSBEQU4gUEVOWUVMRU5HR0FSQUFOIEVMRUtUUklLIFNFUlRBIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBKQUJBVEFOIFBFTkRBRlRBUkFOIE5FR0FSQSAoSlBOKSBEQUVSQUggS1VBTEEgS0FOR1NBUiwgUEVSQUs8L1RhanVrPjxJa2xhblN0YXJ0RGF0ZT4yMDI1LTA2LTE5VDAwOjAwOjAwKzA4OjAwPC9Ja2xhblN0YXJ0RGF0ZT48SWtsYW5FbmREYXRlPjIwMjUtMDYtMjZUMTI6MDA6MDArMDg6MDA8L0lrbGFuRW5kRGF0ZT48U2l0ZVZpc2l0PjI8L1NpdGVWaXNpdD48L1RhYmxlPjxUYWJsZSBkaWZmZ3I6aWQ9IlRhYmxlMTkiIG1zZGF0YTpyb3dPcmRlcj0iMTgiPjxyZWZObz5QUk8yNTA2MDQxNDU5MzMzOTE8L3JlZk5vPjxQcm9Obz5TSC9QL0pLUi9KTU4vU0ZNL01layAxMS8yMDI1PC9Qcm9Obz48VGFqdWs+S0VSSkEtS0VSSkEgUEVNQVNBTkdBTiBCQVJVIFNJU1RFTSBQQU0gVFVCRSBXRUxMIERBTiBQQU0gUEVOR0dBTEFLIFNFUlRBIExBSU4tTEFJTiBLRVJKQSBZQU5HIEJFUktBSVRBTiBESSBQVVNBVCBMQVRJSEFOIFRWRVQgSU5TVElUVVQgUEVSVEFOSUFOIFRJVEkgR0FOVE9ORywgQk9UQSwgUEVSQUsgREFSVUwgUklEWlVBTjwvVGFqdWs+PElrbGFuU3RhcnREYXRlPjIwMjUtMDYtMTJUMDA6MDA6MDArMDg6MDA8L0lrbGFuU3RhcnREYXRlPjxJa2xhbkVuZERhdGU+MjAyNS0wNi0yNFQxMjowMDowMCswODowMDwvSWtsYW5FbmREYXRlPjxTaXRlVmlzaXQ+MTwvU2l0ZVZpc2l0PjwvVGFibGU+PFRhYmxlIGRpZmZncjppZD0iVGFibGUyMCIgbXNkYXRhOnJvd09yZGVyPSIxOSI+PHJlZk5vPlBSTzI1MDYwNDE1MjA1NDQ1MjwvcmVmTm8+PFByb05vPkpLUihFKVBLL1NIKFBZL04pNDIvMjAyNUpMTiAxMTUvMjAyNTwvUHJvTm8+PFRhanVrPktFUkpBLUtFUkpBIE1FTkFJS1RBUkFGIExBTVBVIElTWUFSQVQgU0VSVEEgS0VSSkEtS0VSSkEgQkVSS0FJVEFOIERJIEpBTEFOIEpFTEFQQU5HLUNIRU1PUiAoQTEpIERJIERBRVJBSCBLSU5UQSwgUEVSQUsgREFSVUwgUklEWlVBTjwvVGFqdWs+PElrbGFuU3RhcnREYXRlPjIwMjUtMDYtMTZUMDA6MDA6MDArMDg6MDA8L0lrbGFuU3RhcnREYXRlPjxJa2xhbkVuZERhdGU+MjAyNS0wNi0yM1QxMjowMDowMCswODowMDwvSWtsYW5FbmREYXRlPjxTaXRlVmlzaXQ+MjwvU2l0ZVZpc2l0PjwvVGFibGU+PFRhYmxlIGRpZmZncjppZD0iVGFibGUyMSIgbXNkYXRhOnJvd09yZGVyPSIyMCI+PHJlZk5vPlBSTzI1MDYwNDE4MDUyMTE3MDwvcmVmTm8+PFByb05vPkpLUihFKVBLL1NIKFBKKTA5LzIwMjVKTE4gMTE2LzIwMjU8L1Byb05vPjxUYWp1az5LRVJKQS1LRVJKQSBQRU1BU0FOR0FOIEJBUlUgQkFHSSBMQU1QVSBKRU5JUyBTT0xBUiBMRUQgU0VSVEEgS0VSSkEtS0VSSkEgWUFORyBCRVJLQUlUQU4gREkgTEFMVUFOIFNBQkFLIEJFUk5BTSAtIEhVVEFOIE1FTElOVEFORyBTRUsgNTQ5LjIgSElOR0dBIFNFSyA1NjgsIEpBTEFOIFNJTVBBTkcgRU1QQVQgQkFHQU4gREFUT0sgRlQwNjkgREFFUkFIIEJBR0FOIERBVFVLLCBQRVJBSyBEQVJVTCBSSURaVUFOPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0xNlQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA2LTIzVDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4yPC9TaXRlVmlzaXQ+PC9UYWJsZT48VGFibGUgZGlmZmdyOmlkPSJUYWJsZTIyIiBtc2RhdGE6cm93T3JkZXI9IjIxIj48cmVmTm8+UFJPMjUwNjA5MTcyODE4NzkyPC9yZWZObz48UHJvTm8+SktSLktLLlNILkYgMTUvMjAyNTwvUHJvTm8+PFRhanVrPktFUkpBIE1FTkFJS1RBUkFGIERBTiBVQkFIU1VBSSBQVVNBVCBLRUdJQVRBTiBNQVNZQVJBS0FUIChQS00pIEtFTUFTIFNVTkdBSSBTSVBVVCwgS1VBTEEgS0FOR1NBUiBTRVJUQSBLRVJKQS1LRVJKQSBCRVJLQUlUQU4uPC9UYWp1az48SWtsYW5TdGFydERhdGU+MjAyNS0wNi0xNlQwMDowMDowMCswODowMDwvSWtsYW5TdGFydERhdGU+PElrbGFuRW5kRGF0ZT4yMDI1LTA2LTIzVDEyOjAwOjAwKzA4OjAwPC9Ja2xhbkVuZERhdGU+PFNpdGVWaXNpdD4yPC9TaXRlVmlzaXQ+PC9UYWJsZT48L05ld0RhdGFTZXQ+PC9kaWZmZ3I6ZGlmZmdyYW0+BAMAAAAOU3lzdGVtLlZlcnNpb24EAAAABl9NYWpvcgZfTWlub3IGX0J1aWxkCV9SZXZpc2lvbgAAAAAICAgIAgAAAAAAAAD//////////wseC18hSXRlbUNvdW50AhYfAGcWLAIBD2QWFAIBDw8WAh4EVGV4dAUBMWRkAgUPDxYCHwBoZGQCBw8PFgQfBgUcU0gvTlNDL04vSktSL0pNTi9NZWsgMDMvMjAyNR4LTmF2aWdhdGVVcmwFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxOTEwMDU1NTQ2MWRkAgkPDxYCHwYFkQFTSVNURU0gUEVOWUFNQU4gREFOIFBFTkdBTElIQU4gVURBUkEgQkFHSSBQUk9KRUsgUEVNQklOQUFOIERFV0FOIFNFUkJBR1VOQSBEQU4gS0VSSkEtS0VSSkEgQkVSS0FJVEFOIERJIEtFRElBTUFOIFJBU01JIFkuQS5CLiBNRU5URVJJIEJFU0FSIFBFUkFLZGQCCw8PFgIfBgUSUFJPMjUwNjE5MTAwNTU1NDYxZGQCDQ8PFgIfBgUDIEczZGQCDw8PFgIfBgUEIE0wMWRkAhEPDxYCHwYFBVdhamliZGQCEw8PFgIfBgUBMWRkAhUPDxYCHwYFCzE0IEp1bCAyMDI1ZGQCAg9kFhQCAQ8PFgIfBgUBMmRkAgUPDxYCHwBoZGQCBw8PFgQfBgUcU0gvUC9KS1IvSk1OL1NGTS9NZWsgMTkvMjAyNR8HBSpJa2xhbkRldGFpbHMuYXNweD9yZWZObz1QUk8yNTA2MTcxMDQzNTMzMjhkZAIJDw8WAh8GBdYBS0VSSkEtS0VSSkEgTUVNQkVLQUwsIE1FTUFTQU5HIERBTiBNRU5HVUpJVEVSSU1BIFNJU1RFTSBQRU5ZQU1BTiBVREFSQSBCQUdJIFBST0pFSyBNRU5BSUtUQVJBRiBEQU4gUEVOR1VCQUhTVUFJQU4gUlVBTkcgUEVKQUJBVCBCQUhBUlUgSkFCQVRBTiBQRU5EQUZUQVJBTiBORUdBUkEgKEpQTikgREFFUkFIIEtJTlRBLCBCQVRVIEdBSkFILCBQRVJBSyBEQVJVTCBSSURaVUFOLmRkAgsPDxYCHwYFElBSTzI1MDYxNzEwNDM1MzMyOGRkAg0PDxYCHwYFAyBHMWRkAg8PDxYCHwYFBCBNMDFkZAIRDw8WAh8GBQVXYWppYmRkAhMPDxYCHwYFATFkZAIVDw8WAh8GBQswOSBKdWwgMjAyNWRkAgMPZBYUAgEPDxYCHwYFATNkZAIFDw8WAh8AaGRkAgcPDxYEHwYFF0pLUi5LdGEuUGVyLlNHQiAzNC8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxODA4MzIyNzIzNmRkAgkPDxYCHwYFW0tFUkpBLUtFUkpBIFBFTkdVQkFIU1VBSUFOIFJVQU5HIFBFSkFCQVQgQkFIQVJVIEpBQkFUQU4gUEVOREFGVEFSQU4gTkVHQVJBIChKUE4pIEJBVFUgR0FKQUhkZAILDw8WAh8GBRJQUk8yNTA2MTgwODMyMjcyMzZkZAINDw8WAh8GBQMgRzJkZAIPDw8WAh8GBQQgQjI4ZGQCEQ8PFgIfBgUFV2FqaWJkZAITDw8WAh8GBQExZGQCFQ8PFgIfBgULMDcgSnVsIDIwMjVkZAIED2QWFAIBDw8WAh8GBQE0ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBRJKS1IuQkQuU0guIDA1LzIwMjUfBwUqSWtsYW5EZXRhaWxzLmFzcHg/cmVmTm89UFJPMjUwNjE2MDk0MzAxODU1ZGQCCQ8PFgIfBgXsAUtFUkpBLUtFUkpBIFBFTllFTEVOR0dBUkFBTiBQQVZFTUVOIERFTkdBTiBLQUVEQUggUkVHVUxBVEUgJiBPVkVSTEFZIERBTiBMQUlOLUxBSU4gS0VSSkEgQkVSS0FJVEFOLCBESSBTRyBTQU1BSy1TRyBNQU5JTEEgMSwgTEFMVUFOIEEyNTUsIFNFS1NZRU4gMTMuMDAtMTUuMDAgREFOIERJIEtHIFNHIE1BTklMQSwgTEFMVUFOIEFBMDEsIFNFS1NZRU4gMC4wMC0xLjAwLCBEQUVSQUggQkFHQU4gREFUVUssIFBFUkFLZGQCCw8PFgIfBgUSUFJPMjUwNjE2MDk0MzAxODU1ZGQCDQ8PFgIfBgUDIEcyZGQCDw8PFgIfBgUKIENFMDEgQ0U0MmRkAhEPDxYCHwYFC1RpZGFrIFdhamliZGQCEw8PFgIfBgUBMmRkAhUPDxYCHwYFCzAzIEp1bCAyMDI1ZGQCBQ9kFhQCAQ8PFgIfBgUBNWRkAgUPDxYCHwBoZGQCBw8PFgQfBgUjSktSLkhVLlBLKFVCKShOKTIwLzEwLzI1SkxOIDEwLzIwMjUfBwUqSWtsYW5EZXRhaWxzLmFzcHg/cmVmTm89UFJPMjUwNjE4MTA0NTI2MzIzZGQCCQ8PFgIfBgVeU0VOR0dBUkEgQ0VSVU4gUlVOVFVIIERBTiBLRVJKQS1LRVJKQSBCRVJLQUlUQU4gREkgVEFNQU4gQkFOREFSIEJBUlUgTEVOR0dPTkcsIERBRVJBSCBMRU5HR09OR2RkAgsPDxYCHwYFElBSTzI1MDYxODEwNDUyNjMyM2RkAg0PDxYCHwYFAyBHMmRkAg8PDxYCHwYFBSBDRTA4ZGQCEQ8PFgIfBgUFV2FqaWJkZAITDw8WAh8GBQExZGQCFQ8PFgIfBgULMDMgSnVsIDIwMjVkZAIGD2QWFAIBDw8WAh8GBQE2ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBSNKS1IuSFUuUEsoVUIpKE4pMjAvMTEvMjVKTE4gMTEvMjAyNR8HBSpJa2xhbkRldGFpbHMuYXNweD9yZWZObz1QUk8yNTA2MTgxMDQ3MzQwMjFkZAIJDw8WAh8GBWRTRU5HR0FSQSBDRVJVTiBSVU5UVUggREFOIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBQRVJLQU1QVU5HQU4gVEVSU1VTVU4gQlVLSVQgUkFKQSwgREFFUkFIIExFTkdHT05HZGQCCw8PFgIfBgUSUFJPMjUwNjE4MTA0NzM0MDIxZGQCDQ8PFgIfBgUDIEczZGQCDw8PFgIfBgUFIENFMDhkZAIRDw8WAh8GBQVXYWppYmRkAhMPDxYCHwYFATFkZAIVDw8WAh8GBQswMyBKdWwgMjAyNWRkAgcPZBYUAgEPDxYCHwYFATdkZAIFDw8WAh8AaGRkAgcPDxYEHwYFI0pLUi5IVS5QSyhVQikoTikyMC8xMi8yNUpMTiAxMi8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxODEwNDkwNTM1NGRkAgkPDxYCHwYFVFNFTkdHQVJBIENFUlVOIFJVTlRVSCBEQU4gS0VSSkEtS0VSSkEgQkVSS0FJVEFOIERJIFJQQSBCVUtJVCBTRU5ZVU0sIERBRVJBSCBMRU5HR09OR2RkAgsPDxYCHwYFElBSTzI1MDYxODEwNDkwNTM1NGRkAg0PDxYCHwYFAyBHM2RkAg8PDxYCHwYFBSBDRTA4ZGQCEQ8PFgIfBgUFV2FqaWJkZAITDw8WAh8GBQExZGQCFQ8PFgIfBgULMDMgSnVsIDIwMjVkZAIID2QWFAIBDw8WAh8GBQE4ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBRlKS1IuVVRBL1NIKFRQRylFTEMgNC8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxOTEyNTYxNDc1NGRkAgkPDxYCHwYFkQFLRVJKQS1LRVJKQSAgUEVOWUVMRU5HR0FSQUFOIEVMRUtUUklLIFZPTFRBTiBTRURFUkhBTkEgMTFLViBEQU4gTEFJTi1MQUlOIEtFUkpBIEJFUktBSVRBTiBESSBLRU0tS0VNIFRFTlRFUkEgREFSQVQsIFRBSVBJTkcsIFBFUkFLIERBUlVMIFJJRFpVQU4uZGQCCw8PFgIfBgUSUFJPMjUwNjE5MTI1NjE0NzU0ZGQCDQ8PFgIfBgUJIEcxIEcyIEczZGQCDw8PFgIfBgUMIEUwNCBFMDUgRTExZGQCEQ8PFgIfBgULVGlkYWsgV2FqaWJkZAITDw8WAh8GBQEyZGQCFQ8PFgIfBgULMDEgSnVsIDIwMjVkZAIJD2QWFAIBDw8WAh8GBQE5ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBSJKS1IoRSlQSy9TSChQWSk2MS8yMDI1QkdOIDEyMi8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxODE0MjYzNTc5MWRkAgkPDxYCHwYFwgFLRVJKQS1LRVJKQSBQRU5ZRUxFTkdHQVJBQU4gRUxFS1RSSUsgREFOIFBFTkRBV0FJQU4gU0VNVUxBIFNFUlRBIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBCTE9LIFBFSkFCQVQsIFBVU0FUIFNVTUJFUiBEQU4gU1VSQVUgREkgS09MRUogVk9LQVNJT05BTCBTTElNIFJJVkVSLCBEQUVSQUggTVVBTExJTSwgUEVSQUsgREFSVUwgUklEWlVBTmRkAgsPDxYCHwYFElBSTzI1MDYxODE0MjYzNTc5MWRkAg0PDxYCHwYFEiBHMiBHMyBHNCBHNSBHNiBHN2RkAg8PDxYCHwYFDCBFMDQgRTExIEUxN2RkAhEPDxYCHwYFC1RpZGFrIFdhamliZGQCEw8PFgIfBgUBMmRkAhUPDxYCHwYFCzMwIEp1biAyMDI1ZGQCCg9kFhQCAQ8PFgIfBgUCMTBkZAIFDw8WAh8AaGRkAgcPDxYEHwYFE0pLUi5LUk4uSkxOIDE2LzIwMjUfBwUqSWtsYW5EZXRhaWxzLmFzcHg/cmVmTm89UFJPMjUwNjE4MTcwMzUwNDU1ZGQCCQ8PFgIfBgW0AUtFUkpBIFBFUkFXQVRBTiBBU0FTIEpBTEFOIFlBTkcgTUVOREFQIERBTiBQRU1CQUlLQU4gVElBTkcgTEFNUFUgSVNZQVJBVCBDT05ET05HIFNFUlRBIEtFUkpBIEJFUktBSVRBTiBESSBTRUtTWUVOIDAuNCwgSkFMQU4gS1VBTEEgS1VSQVUgLSBCQUdBTiBTRVJBSSAoRlQwNzUpLCBEQUVSQUggS0VSSUFOLCBQRVJBS2RkAgsPDxYCHwYFElBSTzI1MDYxODE3MDM1MDQ1NWRkAg0PDxYCHwYFAyBHMWRkAg8PDxYCHwYFDyBDRTAxIENFMjEgQ0U0MmRkAhEPDxYCHwYFC1RpZGFrIFdhamliZGQCEw8PFgIfBgUBMmRkAhUPDxYCHwYFCzMwIEp1biAyMDI1ZGQCCw9kFhICAQ8PFgIfBgUCMTFkZAIHDw8WBB8GBRdKS1IuS3RhLk5lZy5TR0IgMzEvMjAyNR8HBSpJa2xhbkRldGFpbHMuYXNweD9yZWZObz1QUk8yNTA1MTYxNTM5MDM1ODZkZAIJDw8WAh8GBXBLRVJKQS1LRVJKQSBVQkFIU1VBSSBSVUFORyBQRUpBQkFUIEJBSEFSVSAoQVJBUyA1KSBKQUJBVEFOIE1VRlRJIE5FR0VSSSBQRVJBSyBEQVJVTCBSSURaVUFOIERJIEJBTkdVTkFOIFNTTSBJUE9IZGQCCw8PFgIfBgUSUFJPMjUwNTE2MTUzOTAzNTg2ZGQCDQ8PFgIfBgUDIEczZGQCDw8PFgIfBgUEIEIyOGRkAhEPDxYCHwYFBVdhamliZGQCEw8PFgIfBgUBMWRkAhUPDxYCHwYFCzI2IEp1biAyMDI1ZGQCDA9kFhQCAQ8PFgIfBgUCMTJkZAIFDw8WAh8AaGRkAgcPDxYEHwYFHFNIL04vSktSL0pNTi9TRk0vTWVrIDIwLzIwMjUfBwUqSWtsYW5EZXRhaWxzLmFzcHg/cmVmTm89UFJPMjUwNjExMTQxOTA1MDM4ZGQCCQ8PFgIfBgV4S0VSSkEtS0VSSkEgTUVOQUlLVEFSQUYgS0VNQVNBTiBEQUxBTUFOIExJRiAoSU5URVJJT1IgREVTSUdOKSBCQUdJIExJRiAyLCBMSUYzIERBTiBMSUYgNiBESSBCQU5HVU5BTiBQRVJBSyBEQVJVTCBSSURaVUFOZGQCCw8PFgIfBgUSUFJPMjUwNjExMTQxOTA1MDM4ZGQCDQ8PFgIfBgUVIEcxIEcyIEczIEc0IEc1IEc2IEc3ZGQCDw8PFgIfBgUEIE0wM2RkAhEPDxYCHwYFBVdhamliZGQCEw8PFgIfBgUBMWRkAhUPDxYCHwYFCzI2IEp1biAyMDI1ZGQCDQ9kFhQCAQ8PFgIfBgUCMTNkZAIFDw8WAh8AaGRkAgcPDxYEHwYFGkpLUi5VVEEvU0goVFBHKUF3YW0gNC8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxMjEwMzk1NzcxMmRkAgkPDxYCHwYFiAFLRVJKQSBQRU1CQUlLQU4gQVdBTSBCQUdJIFNJU1RFTSBCRUtBTEFOIEFJUiBEQU4gU0lTVEVNIFBJTEkgQk9NQkEgREkgUEFTVUtBTiBSRUpJTUVOIEtFLTMgQVJUSUxFUkkgRElSQUpBICgzIFJBRCksIEtFTSBLQU1VTlRJTkcsIFBFUkFLZGQCCw8PFgIfBgUSUFJPMjUwNjEyMTAzOTU3NzEyZGQCDQ8PFgIfBgUDIEcyZGQCDw8PFgIfBgUFIENFMjBkZAIRDw8WAh8GBQtUaWRhayBXYWppYmRkAhMPDxYCHwYFATJkZAIVDw8WAh8GBQsyNiBKdW4gMjAyNWRkAg4PZBYUAgEPDxYCHwYFAjE0ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBSJKS1IoRSlQSy9TSChQWSk2My8yMDI1SkxOIDExOC8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxMzE2NDIwOTA0MWRkAgkPDxYCHwYFtAFLRVJKQS1LRVJKQSBQRU1CQUlLQU4gTEFNUFUgSkFMQU4gVU5UVUsgSkFMQU4gUEVSU0VLVVRVQU4gU0VSVEEgS0VSSkEtS0VSSkEgQkVSS0FJVEFOIERJIEpBTEFOIElQT0ggLSBMVU1VVCBGVCAwMDUgU0VLU1lFTiA2NzQgSElOR0dBIFNFS1NZRU4gNjczLCBQRVJBSyBURU5HQUgsIFBFUkFLIERBUlVMIFJJRFpVQU5kZAILDw8WAh8GBRJQUk8yNTA2MTMxNjQyMDkwNDFkZAINDw8WAh8GBRIgRzIgRzMgRzQgRzUgRzYgRzdkZAIPDw8WAh8GBRAgRTA0IEUxMSBFMTYgRTE3ZGQCEQ8PFgIfBgULVGlkYWsgV2FqaWJkZAITDw8WAh8GBQEyZGQCFQ8PFgIfBgULMjYgSnVuIDIwMjVkZAIPD2QWFAIBDw8WAh8GBQIxNWRkAgUPDxYCHwBoZGQCBw8PFgQfBgUiSktSKEUpUEsvU0goUFkpNjIvMjAyNUpMTiAxMTcvMjAyNR8HBSpJa2xhbkRldGFpbHMuYXNweD9yZWZObz1QUk8yNTA2MTMxNjUwMDM0NDVkZAIJDw8WAh8GBcIBS0VSSkEtS0VSSkEgTkFJS1RBUkFGIERBTiBTRUxFTkdHQVJBIExBTVBVIEpBTEFOIFRFUk1BU1VLIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBMQUxVQU4gRlQwNzYgSkFMQU4gSy4gS0FOR1NBUiAtIEdFUklLIC0gUEVOR0tBTEFOIEhVTFUgKEpBTEFOIEdFUklLIC0gQkFUVSAyIEYvUCAyKSBESSBEQUVSQUggSFVMVSBQRVJBSywgUEVSQUtkZAILDw8WAh8GBRJQUk8yNTA2MTMxNjUwMDM0NDVkZAINDw8WAh8GBQkgRzEgRzIgRzNkZAIPDw8WAh8GBRAgRTA0IEUxMSBFMTYgRTE3ZGQCEQ8PFgIfBgULVGlkYWsgV2FqaWJkZAITDw8WAh8GBQEyZGQCFQ8PFgIfBgULMjYgSnVuIDIwMjVkZAIQD2QWFAIBDw8WAh8GBQIxNmRkAgUPDxYCHwBoZGQCBw8PFgQfBgUkSktSKEUpUEsvU0goUFkvTik0NC8yMDI1SkxOIDExOS8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxNDExMDEyMDg0OWRkAgkPDxYCHwYFiQFLRVJKQS1LRVJKQSBQRU5ZRUxFTkdHQVJBQU4gTEFNUFUgSVNZQVJBVCBESSBKQUxBTiBUQU5KVU5HIE1BTElNIEEwMzAgU0VSVEEgS0VSSkEtS0VSSkEgWUFORyBCRVJLQUlUQU4gREFFUkFIIE1VQUxMSU0gUEVSQUsgREFSVUwgUklEWlVBTmRkAgsPDxYCHwYFElBSTzI1MDYxNDExMDEyMDg0OWRkAg0PDxYCHwYFCSBHMSBHMiBHM2RkAg8PDxYCHwYFECBFMDQgRTExIEUxNiBFMTdkZAIRDw8WAh8GBQtUaWRhayBXYWppYmRkAhMPDxYCHwYFATJkZAIVDw8WAh8GBQsyNiBKdW4gMjAyNWRkAhEPZBYUAgEPDxYCHwYFAjE3ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBSJKS1IoRSlQSy9TSChQWSk1OS8yMDI1QkdOIDEyMS8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxNjEzMTY1MzM0MGRkAgkPDxYCHwYF6gFLRVJKQS1LRVJKQSBQRU5EQVdBSUFOIFNFTVVMQSBFTEVLVFJJSyBEQU4gS0VSSkEtS0VSSkEgQkVSS0FJVEFOIERJIFBFSkFCQVQgQkFSVSBKQUJBVEFOIFBFTkRBRlRBUkFOIE5FR0FSQSAoSlBOKSBCQVRVIEdBSkFIIEJFUkFMQU1BVCBOTyA2ICYgNyAoR1JPVU5EIEZMT09SKSwgUEVSU0lBUkFOIEJBVFUgR0FKQUggUEVSREFOQSAxLCBQVVNBVCBLT01FUlNJQUwsIEJBVFUgR0FKQUggUEVSREFOQSwgUEVSQUtkZAILDw8WAh8GBRJQUk8yNTA2MTYxMzE2NTMzNDBkZAINDw8WAh8GBQkgRzEgRzIgRzNkZAIPDw8WAh8GBQwgRTA0IEUxMSBFMTdkZAIRDw8WAh8GBQtUaWRhayBXYWppYmRkAhMPDxYCHwYFATJkZAIVDw8WAh8GBQsyNiBKdW4gMjAyNWRkAhIPZBYUAgEPDxYCHwYFAjE4ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBSJKS1IoRSlQSy9TSChQWSk2NC8yMDI1QkdOIDEyMC8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYxNzA5NDIyNjM3NWRkAgkPDxYCHwYFlgFLRVJKQS1LRVJKQSBQRU5EQVdBSUFOIFNFTVVMQSBEQU4gUEVOWUVMRU5HR0FSQUFOIEVMRUtUUklLIFNFUlRBIEtFUkpBLUtFUkpBIEJFUktBSVRBTiBESSBKQUJBVEFOIFBFTkRBRlRBUkFOIE5FR0FSQSAoSlBOKSBEQUVSQUggS1VBTEEgS0FOR1NBUiwgUEVSQUtkZAILDw8WAh8GBRJQUk8yNTA2MTcwOTQyMjYzNzVkZAINDw8WAh8GBQkgRzEgRzIgRzNkZAIPDw8WAh8GBQwgRTA0IEUxMSBFMTdkZAIRDw8WAh8GBQtUaWRhayBXYWppYmRkAhMPDxYCHwYFATJkZAIVDw8WAh8GBQsyNiBKdW4gMjAyNWRkAhMPZBYUAgEPDxYCHwYFAjE5ZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBRxTSC9QL0pLUi9KTU4vU0ZNL01layAxMS8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYwNDE0NTkzMzM5MWRkAgkPDxYCHwYFuAFLRVJKQS1LRVJKQSBQRU1BU0FOR0FOIEJBUlUgU0lTVEVNIFBBTSBUVUJFIFdFTEwgREFOIFBBTSBQRU5HR0FMQUsgU0VSVEEgTEFJTi1MQUlOIEtFUkpBIFlBTkcgQkVSS0FJVEFOIERJIFBVU0FUIExBVElIQU4gVFZFVCBJTlNUSVRVVCBQRVJUQU5JQU4gVElUSSBHQU5UT05HLCBCT1RBLCBQRVJBSyBEQVJVTCBSSURaVUFOZGQCCw8PFgIfBgUSUFJPMjUwNjA0MTQ1OTMzMzkxZGQCDQ8PFgIfBgUDIEcyZGQCDw8PFgIfBgUIIE0yMiBNMTVkZAIRDw8WAh8GBQVXYWppYmRkAhMPDxYCHwYFATFkZAIVDw8WAh8GBQsyNCBKdW4gMjAyNWRkAhQPZBYUAgEPDxYCHwYFAjIwZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBSRKS1IoRSlQSy9TSChQWS9OKTQyLzIwMjVKTE4gMTE1LzIwMjUfBwUqSWtsYW5EZXRhaWxzLmFzcHg/cmVmTm89UFJPMjUwNjA0MTUyMDU0NDUyZGQCCQ8PFgIfBgWEAUtFUkpBLUtFUkpBIE1FTkFJS1RBUkFGIExBTVBVIElTWUFSQVQgU0VSVEEgS0VSSkEtS0VSSkEgQkVSS0FJVEFOIERJIEpBTEFOIEpFTEFQQU5HLUNIRU1PUiAoQTEpIERJIERBRVJBSCBLSU5UQSwgUEVSQUsgREFSVUwgUklEWlVBTmRkAgsPDxYCHwYFElBSTzI1MDYwNDE1MjA1NDQ1MmRkAg0PDxYCHwYFEiBHMiBHMyBHNCBHNSBHNiBHN2RkAg8PDxYCHwYFECBFMDQgRTExIEUxNiBFMTdkZAIRDw8WAh8GBQtUaWRhayBXYWppYmRkAhMPDxYCHwYFATJkZAIVDw8WAh8GBQsyMyBKdW4gMjAyNWRkAhUPZBYUAgEPDxYCHwYFAjIxZGQCBQ8PFgIfAGhkZAIHDw8WBB8GBSJKS1IoRSlQSy9TSChQSikwOS8yMDI1SkxOIDExNi8yMDI1HwcFKklrbGFuRGV0YWlscy5hc3B4P3JlZk5vPVBSTzI1MDYwNDE4MDUyMTE3MGRkAgkPDxYCHwYF6AFLRVJKQS1LRVJKQSBQRU1BU0FOR0FOIEJBUlUgQkFHSSBMQU1QVSBKRU5JUyBTT0xBUiBMRUQgU0VSVEEgS0VSSkEtS0VSSkEgWUFORyBCRVJLQUlUQU4gREkgTEFMVUFOIFNBQkFLIEJFUk5BTSAtIEhVVEFOIE1FTElOVEFORyBTRUsgNTQ5LjIgSElOR0dBIFNFSyA1NjgsIEpBTEFOIFNJTVBBTkcgRU1QQVQgQkFHQU4gREFUT0sgRlQwNjkgREFFUkFIIEJBR0FOIERBVFVLLCBQRVJBSyBEQVJVTCBSSURaVUFOZGQCCw8PFgIfBgUSUFJPMjUwNjA0MTgwNTIxMTcwZGQCDQ8PFgIfBgUJIEcxIEcyIEczZGQCDw8PFgIfBgUQIEUwNCBFMTEgRTE2IEUxN2RkAhEPDxYCHwYFC1RpZGFrIFdhamliZGQCEw8PFgIfBgUBMmRkAhUPDxYCHwYFCzIzIEp1biAyMDI1ZGQCFg9kFhQCAQ8PFgIfBgUCMjJkZAIFDw8WAh8AaGRkAgcPDxYEHwYFE0pLUi5LSy5TSC5GIDE1LzIwMjUfBwUqSWtsYW5EZXRhaWxzLmFzcHg/cmVmTm89UFJPMjUwNjA5MTcyODE4NzkyZGQCCQ8PFgIfBgV9S0VSSkEgTUVOQUlLVEFSQUYgREFOIFVCQUhTVUFJIFBVU0FUIEtFR0lBVEFOIE1BU1lBUkFLQVQgKFBLTSkgS0VNQVMgU1VOR0FJIFNJUFVULCBLVUFMQSBLQU5HU0FSIFNFUlRBIEtFUkpBLUtFUkpBIEJFUktBSVRBTi5kZAILDw8WAh8GBRJQUk8yNTA2MDkxNzI4MTg3OTJkZAINDw8WAh8GBQMgRzJkZAIPDw8WAh8GBQwgQjA0IEIyNCBCMjhkZAIRDw8WAh8GBQtUaWRhayBXYWppYmRkAhMPDxYCHwYFATJkZAIVDw8WAh8GBQsyMyBKdW4gMjAyNWRkAgEPZBYCZg9kFgICAQ8UKwACZBAWABYAFgBkAg0PZBYEZg9kFgJmD2QWBAIBDw8WAh8AaGRkAgMPFgYfAWYfAgIFHwBoZAIBD2QWAmYPZBYCAgEPFCsAAmQQFgAWABYAZBgDBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WBAUXY3RsMDAkTWFpbkNvbnRlbnQkYnRuVU0FEmN0bDAwJEltYWdlQnV0dG9uMQUMY3RsMDAkYnRuSW1nBQ1jdGwwMCRidG5JbWcyBRxjdGwwMCRNYWluQ29udGVudCREYXRhUGFnZXIyDxQrAARkZAIFZmQFHGN0bDAwJE1haW5Db250ZW50JERhdGFQYWdlcjEPFCsABGQCBwIHAhZkaSJJI7JzGxFC4ZlTRtbk/3/+5LYxHfB9N/2N0m05wq8=">
</div>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['form1'];
if (!theForm) {
    theForm = document.form1;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>


<script src="/WebResource.axd?d=Gh2qVuG-OKdjxfj5zt8otS8OVDzC-Bpc4wXW99z2W0eylwrXJcSI3mcT4BuHsMov_wizXgQc2ctzUesokTJUMe2z-vhoTvT0msUGr-PUS181&amp;t=638563559773552689" type="text/javascript"></script>


<script src="/ScriptResource.axd?d=ZPj23NPM5cmkB3CEtfQbVFWKRDMtxr5NbgADxOqn156oV1n3o085H5Ag_hZBdVrun4loHhixOkd0YsVMVrRD74KR1q0zsQXPFetSPbQNxzckUSJ8pYPwr76hbrtLu_jfueXd69LwqaqDBsWXDBUOAQ2&amp;t=5f8643ea" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
if (typeof(Sys) === 'undefined') throw new Error('ASP.NET Ajax client-side framework failed to load.');
//]]>
</script>

<script src="/ScriptResource.axd?d=CLh_6r7pLdRFsCD0aQQ47yDqNHB68xd6yAQS7kQ327IIXT0swK9wvlYGVD1b9SIwzVyNN2KRqQ4DhuG0y3e4CJm6cYO5EPIykpT0LWZzoM3ZWselH9N7jjOieMfb0GtispOc7V1xZfQGzLqlvu2mng2&amp;t=5f8643ea" type="text/javascript"></script>
<div class="aspNetHidden">

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="0C32CE3C">
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdAB8Yas8l3Xa8AH5r7N3k2an3sVIc3Wv3w94hW4IAFoX8MhK+1DI9ItjGxu9Hon7E/FsaYicoD5ZhGAS63ZpswYCokVHT2Tba0votFL+w81DTm1L1zOlPZMtd0xtRz87qvFGuw/WNaEqUDME13Jar+fV+Aw2w4g8ttMMnuhh9rIrrj4DUQrE7UQIjMaTUNWw1AKznaM1NDaDCyencWQLGh3q01Fc+CkHmbyw5Zl/vvR2DxVybkmLuPSYYrNoCzPNVKL0nLlfLpLQgHQ8rFnux0gLgph9Gdj9sq7rWD1qYzFzm8z3CwPeCIAudZa6GBE5YuFhSipyVUv4bhuHqyManJHpUFHlBoF6uG/uSSvdzrNiG5JS3eIcjObwpNzElUc5wigHtyIB+96zrR8f9JD6+ijjUMC23Un5iXeDlDVCmc0KrSuOwb1R/nYhfOLY9sTmYJLg5NuQ743pH8rM1DfWL2FHP/DtlnpnezLvfkmMxIPFHrymbNxRl9Y/BMlP/WpGQL1bviwsCoQCkBhr3A2ZNi82SkGSJ12NXkb7i8tSngDAIEabnt6t8rrpBQbB0q2+N9j9O2fvFcb1MW8LfKcP2BUShD4zZrxX92uOlyIx1SyGTQtTH6PWE1tRUfGvWBTM9jkgzw3KAAvomD9y0D8Gah1hRdoHpFcB4VV9jXEIeYjZSb4Tr7AjIPccQbmnF1Efcx6c=">
</div>
    <script type="text/javascript">
//<![CDATA[
Sys.WebForms.PageRequestManager._initialize('ctl00$ToolkitScriptManager1', 'form1', [], [], [], 90, 'ctl00');
//]]>
</script>

    <div id="header">
        <div>
            <div class="logo" align="left">
                <a href=""></a>
            </div>
        </div>
    </div>
    <div id="menus">
        <table align="center" cellspacing="0" width="100%">
            <tbody><tr>
                <td>
                    <div id="menu">
                        <div id="menu-wrapper">
                            <ul>
                                <li class="current_page_item">
                                                                    
                                <a href="Default.aspx">Laman Utama</a> 
                                </li>
                                <li><a href="IklanList.aspx">Sebut Harga</a></li> 
                                <li><a href="RegNew.aspx?opt=0">Kontraktor</a></li>     
				<li><a href="DirectoryList.aspx">Direktori</a></li>                             
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody></table>
    </div>
    <div id="contents">
        <div>
            
            
        </div>
        <div class="main">
            
    <div class="post">
        <table width="100%" align="center" class="l2">
            <tbody><tr>
                <td>
                    <img border="0" src="img/ictask.png" style="height: 28px; width: 28px">
                    <span id="MainContent_lblHeader" class="l3">IKLAN SEBUTHARGA SEMASA </span>
                </td>
                <td align="right">
                    <a id="MainContent_btn1" href="javascript:__doPostBack('ctl00$MainContent$btn1','')">Iklan Semasa</a>
                    &nbsp;|&nbsp;
                    <a id="MainContent_btn2" href="javascript:__doPostBack('ctl00$MainContent$btn2','')">Keputusan</a>
                    &nbsp;|&nbsp;                    
                    <input type="image" name="ctl00$MainContent$btnUM" id="MainContent_btnUM" title="Panduan Pengguna" src="img/timer.png" onclick="aspnetForm.target ='_blank';">
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <hr>
                </td>
            </tr>
            <tr id="MainContent_tr1">
	<td width="35%">
                    <span id="MainContent_Label5">Organisasi:</span>
                    <select name="ctl00$MainContent$dlJabatan" onchange="javascript:setTimeout('__doPostBack(\'ctl00$MainContent$dlJabatan\',\'\')', 0)" id="MainContent_dlJabatan" class="l2" style="width:73%;">
		<option value="1">Pejabat Setiausaha Kerajaan Negeri Perak</option>
		<option selected="selected" value="2">Jabatan Kerja Raya</option>
		<option value="3">Pejabat Daerah Dan Tanah</option>
		<option value="4">Jabatan Pengairan Dan Saliran</option>
		<option value="5">Lembaga Perumahan dan Hartanah</option>
		<option value="8">Jabatan Pertanian</option>

	</select>
                </td>
	<td width="65%">
                    <select name="ctl00$MainContent$dlDaerah" onchange="javascript:setTimeout('__doPostBack(\'ctl00$MainContent$dlDaerah\',\'\')', 0)" id="MainContent_dlDaerah" class="l2" style="width:35%;">
		<option value="78">Bagan Datuk</option>
		<option value="73">Batang Padang</option>
		<option value="72">Hilir Perak</option>
		<option value="71">Hulu Perak (Gerik)</option>
		<option value="77">Kampar</option>
		<option value="70">Kerian</option>
		<option value="68">Kinta</option>
		<option value="69">Kuala Kangsar</option>
		<option value="74">Larut, Matang Dan Selama</option>
		<option value="67">Manjung</option>
		<option value="76">Muallim</option>
		<option selected="selected" value="66">Negeri Perak</option>
		<option value="75">Perak Tengah</option>

	</select>
                    
                    
                </td>
</tr>

            <tr>
                <td colspan="2" valign="top">
                    <table id="MainContent_tbl1" width="100%">
	<tbody><tr class="l5">
		<td colspan="3">
                                
                                
                                        <table class="gv" width="100%" cellspacing="0" cellpadding="5">
                                            <tbody><tr class="gvh">
                                                <td width="10%" align="center">
                                                    <span id="MainContent_lApplication_Label31">No</span>
                                                </td>
                                                <td width="55%">
                                                    <span id="MainContent_lApplication_Label32">Tajuk Sebutharga</span>
                                                </td>
                                                <td width="10%" align="center">
                                                    <span id="MainContent_lApplication_Label2">Gred - Pengkhususan</span>
                                                </td>
                                                <td width="10%" align="center">
                                                    <span id="MainContent_lApplication_Label10">Lawatan Tapak</span>
                                                </td>
                                                <td width="15%" align="center">
                                                    <span id="MainContent_lApplication_Label6">Tarikh Tutup</span>
                                                </td>
                                            </tr>
                                    
                                        <tr class="gva">
                                            <td valign="top" align="center">
                                                <span id="MainContent_lApplication_Label60_7">8</span>
                                            </td>
                                            <td valign="top">
                                                
                                                <img id="MainContent_lApplication_lCode2_7" title="Notis Sebutharga" src="img/print.png" style="height:16px;width:16px;">
                                                
                                                &nbsp;
                                                <a id="MainContent_lApplication_lCode_7" href="IklanDetails.aspx?refNo=PRO250619125614754" style="color:Blue;">JKR.UTA/SH(TPG)ELC 4/2025</a>
                                                <br>
                                                <span id="MainContent_lApplication_Label1_7">KERJA-KERJA  PENYELENGGARAAN ELEKTRIK VOLTAN SEDERHANA 11KV DAN LAIN-LAIN KERJA BERKAITAN DI KEM-KEM TENTERA DARAT, TAIPING, PERAK DARUL RIDZUAN.</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_tGred_7"> G1 G2 G3</span>
                                                <br>
                                                <span id="MainContent_lApplication_tGred2_7"> E04 E05 E11</span>
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_lSv_7">Tidak Wajib</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_Label7_7">01 Jul 2025</span>
                                            </td>
                                        </tr>
                                    
                                        <tr class="gvr">
                                            <td valign="top" align="center">
                                                <span id="MainContent_lApplication_Label60_8">9</span>
                                            </td>
                                            <td valign="top">
                                                
                                                <img id="MainContent_lApplication_lCode2_8" title="Notis Sebutharga" src="img/print.png" style="height:16px;width:16px;">
                                                
                                                &nbsp;
                                                <a id="MainContent_lApplication_lCode_8" href="IklanDetails.aspx?refNo=PRO250618142635791" style="color:Blue;">JKR(E)PK/SH(PY)61/2025BGN 122/2025</a>
                                                <br>
                                                <span id="MainContent_lApplication_Label1_8">KERJA-KERJA PENYELENGGARAAN ELEKTRIK DAN PENDAWAIAN SEMULA SERTA KERJA-KERJA BERKAITAN DI BLOK PEJABAT, PUSAT SUMBER DAN SURAU DI KOLEJ VOKASIONAL SLIM RIVER, DAERAH MUALLIM, PERAK DARUL RIDZUAN</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_tGred_8"> G2 G3 G4 G5 G6 G7</span>
                                                <br>
                                                <span id="MainContent_lApplication_tGred2_8"> E04 E11 E17</span>
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_lSv_8">Tidak Wajib</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_Label4_8">30 Jun 2025</span>
                                            </td>
                                        </tr>
                                    
                                        <tr class="gva">
                                            <td valign="top" align="center">
                                                <span id="MainContent_lApplication_Label60_9">10</span>
                                            </td>
                                            <td valign="top">
                                                
                                                <img id="MainContent_lApplication_lCode2_9" title="Notis Sebutharga" src="img/print.png" style="height:16px;width:16px;">
                                                
                                                &nbsp;
                                                <a id="MainContent_lApplication_lCode_9" href="IklanDetails.aspx?refNo=PRO250618170350455" style="color:Blue;">JKR.KRN.JLN 16/2025</a>
                                                <br>
                                                <span id="MainContent_lApplication_Label1_9">KERJA PERAWATAN ASAS JALAN YANG MENDAP DAN PEMBAIKAN TIANG LAMPU ISYARAT CONDONG SERTA KERJA BERKAITAN DI SEKSYEN 0.4, JALAN KUALA KURAU - BAGAN SERAI (FT075), DAERAH KERIAN, PERAK</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_tGred_9"> G1</span>
                                                <br>
                                                <span id="MainContent_lApplication_tGred2_9"> CE01 CE21 CE42</span>
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_lSv_9">Tidak Wajib</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_Label7_9">30 Jun 2025</span>
                                            </td>
                                        </tr>
                                    
                                        <tr class="gvr">
                                            <td valign="top" align="center">
                                                <span id="MainContent_lApplication_Label60_10">11</span>
                                            </td>
                                            <td valign="top">
                                                
                                                <img id="MainContent_lApplication_lCode2_10" title="Notis Sebutharga" src="img/print.png" style="height:16px;width:16px;">
                                                <img id="MainContent_lApplication_btnImg_10" title="Notis Sebutharga - Ralat" src="img/icon_warning.gif" style="height:16px;width:16px;">
                                                &nbsp;
                                                <a id="MainContent_lApplication_lCode_10" href="IklanDetails.aspx?refNo=PRO250516153903586" style="color:Blue;">JKR.Kta.Neg.SGB 31/2025</a>
                                                <br>
                                                <span id="MainContent_lApplication_Label1_10">KERJA-KERJA UBAHSUAI RUANG PEJABAT BAHARU (ARAS 5) JABATAN MUFTI NEGERI PERAK DARUL RIDZUAN DI BANGUNAN SSM IPOH</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_tGred_10"> G3</span>
                                                <br>
                                                <span id="MainContent_lApplication_tGred2_10"> B28</span>
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_lSv_10">Wajib</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_Label4_10">26 Jun 2025</span>
                                            </td>
                                        </tr>
                                    
                                        <tr class="gva">
                                            <td valign="top" align="center">
                                                <span id="MainContent_lApplication_Label60_11">12</span>
                                            </td>
                                            <td valign="top">
                                                
                                                <img id="MainContent_lApplication_lCode2_11" title="Notis Sebutharga" src="img/print.png" style="height:16px;width:16px;">
                                                
                                                &nbsp;
                                                <a id="MainContent_lApplication_lCode_11" href="IklanDetails.aspx?refNo=PRO250611141905038" style="color:Blue;">SH/N/JKR/JMN/SFM/Mek 20/2025</a>
                                                <br>
                                                <span id="MainContent_lApplication_Label1_11">KERJA-KERJA MENAIKTARAF KEMASAN DALAMAN LIF (INTERIOR DESIGN) BAGI LIF 2, LIF3 DAN LIF 6 DI BANGUNAN PERAK DARUL RIDZUAN</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_tGred_11"> G1 G2 G3 G4 G5 G6 G7</span>
                                                <br>
                                                <span id="MainContent_lApplication_tGred2_11"> M03</span>
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_lSv_11">Wajib</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_Label7_11">26 Jun 2025</span>
                                            </td>
                                        </tr>
                                    
                                        <tr class="gvr">
                                            <td valign="top" align="center">
                                                <span id="MainContent_lApplication_Label60_12">13</span>
                                            </td>
                                            <td valign="top">
                                                
                                                <img id="MainContent_lApplication_lCode2_12" title="Notis Sebutharga" src="img/print.png" style="height:16px;width:16px;">
                                                
                                                &nbsp;
                                                <a id="MainContent_lApplication_lCode_12" href="IklanDetails.aspx?refNo=PRO250612103957712" style="color:Blue;">JKR.UTA/SH(TPG)Awam 4/2025</a>
                                                <br>
                                                <span id="MainContent_lApplication_Label1_12">KERJA PEMBAIKAN AWAM BAGI SISTEM BEKALAN AIR DAN SISTEM PILI BOMBA DI PASUKAN REJIMEN KE-3 ARTILERI DIRAJA (3 RAD), KEM KAMUNTING, PERAK</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_tGred_12"> G2</span>
                                                <br>
                                                <span id="MainContent_lApplication_tGred2_12"> CE20</span>
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_lSv_12">Tidak Wajib</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_Label4_12">26 Jun 2025</span>
                                            </td>
                                        </tr>
                                    
                                        <tr class="gva">
                                            <td valign="top" align="center">
                                                <span id="MainContent_lApplication_Label60_13">14</span>
                                            </td>
                                            <td valign="top">
                                                
                                                <img id="MainContent_lApplication_lCode2_13" title="Notis Sebutharga" src="img/print.png" style="height:16px;width:16px;">
                                                
                                                &nbsp;
                                                <a id="MainContent_lApplication_lCode_13" href="IklanDetails.aspx?refNo=PRO250613164209041" style="color:Blue;">JKR(E)PK/SH(PY)63/2025JLN 118/2025</a>
                                                <br>
                                                <span id="MainContent_lApplication_Label1_13">KERJA-KERJA PEMBAIKAN LAMPU JALAN UNTUK JALAN PERSEKUTUAN SERTA KERJA-KERJA BERKAITAN DI JALAN IPOH - LUMUT FT 005 SEKSYEN 674 HINGGA SEKSYEN 673, PERAK TENGAH, PERAK DARUL RIDZUAN</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_tGred_13"> G2 G3 G4 G5 G6 G7</span>
                                                <br>
                                                <span id="MainContent_lApplication_tGred2_13"> E04 E11 E16 E17</span>
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_lSv_13">Tidak Wajib</span>
                                                
                                            </td>
                                            <td align="center">
                                                <span id="MainContent_lApplication_Label7_13">26 Jun 2025</span>
                                            </td>
                                        </tr>
                                    
                                        </tbody></table>
                                    
                            </td>
	</tr>
	<tr>
		<td align="center" colspan="5">
                                <span id="MainContent_DataPager1"><a href="javascript:__doPostBack('ctl00$MainContent$DataPager1$ctl00$ctl00','')">1</a>&nbsp;<span>2</span>&nbsp;<a href="javascript:__doPostBack('ctl00$MainContent$DataPager1$ctl00$ctl02','')">3</a>&nbsp;<a href="javascript:__doPostBack('ctl00$MainContent$DataPager1$ctl00$ctl03','')">4</a>&nbsp;</span>
                            </td>
	</tr>
</tbody></table>

                    
                </td>
            </tr>
        </tbody></table>
    </div>

        </div>
    </div>
    <div id="adbox">
        <div class="clearfix">
            <div class="items">
                <div class="box col2 web">
                    <h4>
                        <span id="Label3" class="l3">PENAFIAN</span></h4>
                    <p style="font-size: 14px; text-align: justify;">
                        <input type="image" name="ctl00$ImageButton1" id="ImageButton1" src="img/favicon.png" style="height:24px;width:24px;">
                        Pihak Pejabat Setiauasaha Negeri Perak tidak akan bertanggungjawab di atas 
                        sebarang kehilangan data atau kerugian yang berlaku disebabkan oleh penggunaan portal ini.
                    </p>
                </div>
                <div class="box col2 web">
                    <h4>
                        <span id="Label9" class="l3">PAPARAN TERBAIK</span>
                    </h4>
                    <p style="font-family: 'Leelawadee UI'; font-size: 14px;">
                        Sila gunakan Google Chrome
                        <input type="image" name="ctl00$btnImg" id="btnImg" src="img/chrome.png" style="height:24px;width:24px;">
                        atau Mozilla Firefox 2.0 dan ke atas pada resolusi skrin 1024x768.
                    </p>
                </div>
                <div class="box col2 web">
                    <h4>
                        <span id="Label4" class="l3">KEPERLUAN PERISIAN</span></h4>
                    <p style="font-size: 14px;">
                        Perisian yang diperlukan adalah Adobe Reader
                        <input type="image" name="ctl00$btnImg2" id="btnImg2" src="img/adobe.png" style="height:24px;width:24px;">
                        untuk paparan dokumen yang perlu dimuatturun.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div id="footer">
        <div class="clearfix">
            <div id="connect">
                <p>
                    Hubungi Kami: 
                    <img id="Image4" src="img/user.png">
                    <a href="http://helpdeskict.perak.gov.my/index_nolog.php?id=1" target="_blank">
                        <span id="Label5" style="color:White;">http://helpdeskict.perak.gov.my</span>
                     </a>
                </p>
                
            </div>
            
            <p>
                Copyright © 2023 Hakcipta Terpelihara Kerajaan Negeri Perak.
            </p>
        </div>
    </div>
    <!-- end #footer -->
    

<script type="text/javascript">
//<![CDATA[
(function() {var fn = function() {$get('ToolkitScriptManager1_HiddenField').value = '';Sys.Application.remove_init(fn);};Sys.Application.add_init(fn);})();//]]>
</script>
</form>